version: "3.9"

services:
  proxy:
    volumes:
      - ${DATA_DIR}/${COMPOSE_PROJECT_NAME}/frontend:/app

  frontend:
    build:
      context: ${SUBMODULE_DIR}/build-templates/${FRONTEND_BUILD_MODE}
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: rapydo/${FRONTEND_BUILD_MODE}:${RAPYDO_VERSION}
    healthcheck:
      test: "wget -t 1 --quiet --no-check-certificate http://localhost:8080 -O - > /dev/null"
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 10s
      retries: 3
      start_period: 5m
    hostname: angular
    networks:
      default:
        aliases:
          - frontend.dockerized.io
    environment:
      ACTIVATE: ${ACTIVATE_ANGULAR}
      CURRENT_UID: ${CURRENT_UID}
      CURRENT_GID: ${CURRENT_GID}
      APP_MODE: ${APP_MODE}
      VERSION: ${PROJECT_VERSION}
      BUILD: ${BUILD}
      RAPYDO_VERSION: ${RAPYDO_VERSION}
      PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      PROJECT_TITLE: "${PROJECT_TITLE}"
      PROJECT_DESCRIPTION: "${PROJECT_DESCRIPTION}"
      PROJECT_KEYWORDS: "${PROJECT_KEYWORDS}"
      ENABLE_ANGULAR_SSR: ${ENABLE_ANGULAR_SSR}
      FORCE_SSR_SERVER_MODE: ${FORCE_SSR_SERVER_MODE}
      SHOW_LOGIN: ${SHOW_LOGIN}
      ENABLE_FOOTER: ${ENABLE_FOOTER}
      ALLOW_PASSWORD_RESET: ${ALLOW_PASSWORD_RESET}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
      ALLOW_TERMS_OF_USE: ${ALLOW_TERMS_OF_USE}
      AUTH_ENABLE: ${ACTIVATE_AUTH}
      AUTH_MIN_PASSWORD_LENGTH: ${AUTH_MIN_PASSWORD_LENGTH}
      BACKEND_URI: "${BACKEND_URI}"
      BACKEND_PORT: ${BACKEND_API_PORT}
      BACKEND_HOST: ${PROJECT_DOMAIN}
      BACKEND_PREFIX: "${BACKEND_PREFIX}"
      BASE_HREF: ${PROJECT_DOMAIN}
      FRONTEND_PREFIX: ${FRONTEND_PREFIX}
      PUSHPIN_HOST: ${PROJECT_DOMAIN}
      PUSHPIN_PORT: ${PUSHPIN_PORT}
      SENTRY_URL: ${SENTRY_URL}
      GA_TRACKING_CODE: ${GA_TRACKING_CODE}

      CYPRESS_AUTH_DEFAULT_USERNAME: ${AUTH_DEFAULT_USERNAME}
      CYPRESS_AUTH_DEFAULT_PASSWORD: ${AUTH_DEFAULT_PASSWORD}
      CYPRESS_AUTH_FORCE_FIRST_PASSWORD_CHANGE: ${AUTH_FORCE_FIRST_PASSWORD_CHANGE}
      CYPRESS_SHOW_LOGIN: ${SHOW_LOGIN}
      CYPRESS_ALLOW_PASSWORD_RESET: ${ALLOW_PASSWORD_RESET}
      CYPRESS_ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
      CYPRESS_ALLOW_TERMS_OF_USE: ${ALLOW_TERMS_OF_USE}
      CYPRESS_AUTH_ENABLE: ${ACTIVATE_AUTH}
      CYPRESS_AUTH_MIN_PASSWORD_LENGTH: ${AUTH_MIN_PASSWORD_LENGTH}
      CYPRESS_AUTH_MAX_PASSWORD_VALIDITY: ${AUTH_MAX_PASSWORD_VALIDITY}
      CYPRESS_AUTH_DISABLE_UNUSED_CREDENTIALS_AFTER: ${AUTH_DISABLE_UNUSED_CREDENTIALS_AFTER}
      CYPRESS_AUTH_SECOND_FACTOR_AUTHENTICATION: ${AUTH_SECOND_FACTOR_AUTHENTICATION}
      CYPRESS_AUTH_MAX_LOGIN_ATTEMPTS: ${AUTH_MAX_LOGIN_ATTEMPTS}
      CYPRESS_AUTH_LOGIN_BAN_TIME: ${AUTH_LOGIN_BAN_TIME}
      CYPRESS_TESTING_TOTP_HASH:

      CYPRESS_BACKEND_HOST: ${FLASK_HOST}
      CYPRESS_API_URL: http://${FLASK_HOST}:${BACKEND_PORT}/
      # FROM ENV, USED BY CYPRESS TO RECORD RESULTS:
      GITHUB_ACTIONS:
      GITHUB_RUN_ID:
      CYPRESS_RECORD_KEY:
      CYPRESS_PROJECT_ID:
      COMMIT_INFO_BRANCH:
      COMMIT_INFO_MESSAGE:
      COMMIT_INFO_SUBJECT:
      COMMIT_INFO_BODY:
      COMMIT_INFO_EMAIL: "Unknown" # Not provided
      COMMIT_INFO_AUTHOR:
      COMMIT_INFO_SHA:
      COMMIT_INFO_TIMESTAMP:
      COMMIT_INFO_REMOTE:

      # Force xterm to prevent:
      # `tput: No value for $TERM and no -T specified`
      # Raised when running Cypress on non-tty shells
      TERM: xterm

      # DISPLAY: ":0"

    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix:ro
      # - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ${SUBMODULE_DIR}/rapydo-angular/utility:/rapydo

      - ${DATA_DIR}/${COMPOSE_PROJECT_NAME}/frontend:/app
      - ${DATA_DIR}/${COMPOSE_PROJECT_NAME}/karma:/coverage
      # Output folder, configured in cypress.json
      - ${DATA_DIR}/${COMPOSE_PROJECT_NAME}/cypress:/cypress

      - ${SUBMODULE_DIR}/rapydo-angular/karma.conf.js:/app/karma.conf.js
      - ${SUBMODULE_DIR}/rapydo-angular/polyfills.ts:/app/polyfills.ts
      - ${SUBMODULE_DIR}/rapydo-angular/tsconfig.json:/app/tsconfig.json
      - ${SUBMODULE_DIR}/rapydo-angular/tsconfig.app.json:/app/tsconfig.app.json
      - ${SUBMODULE_DIR}/rapydo-angular/tsconfig.server.json:/app/tsconfig.server.json
      - ${SUBMODULE_DIR}/rapydo-angular/tsconfig.spec.json:/app/tsconfig.spec.json
      - ${SUBMODULE_DIR}/rapydo-angular/courtesy:/app/courtesy

      - ${SUBMODULE_DIR}/rapydo-angular/src:/app/app/rapydo
      - ${PROJECT_DIR}/frontend:/app/app/custom

      - ${SUBMODULE_DIR}/rapydo-angular/cypress.json:/app/cypress.json
      - ${SUBMODULE_DIR}/rapydo-angular/cypress/tsconfig.json:/app/cypress/tsconfig.json
      - ${SUBMODULE_DIR}/rapydo-angular/cypress/coverage.webpack.js:/app/cypress/coverage.webpack.js
      - ${SUBMODULE_DIR}/rapydo-angular/cypress/support:/app/cypress/support
      - ${SUBMODULE_DIR}/rapydo-angular/cypress/plugins:/app/cypress/plugins
      - ${SUBMODULE_DIR}/rapydo-angular/cypress/fixtures:/app/cypress/fixtures
      - ${SUBMODULE_DIR}/rapydo-angular/cypress/integration:/app/cypress/integration/rapydo
      - ${PROJECT_DIR}/frontend/integration:/app/cypress/integration/custom

      - ${DATA_DIR}/logs:/logs
