version: '3'

services:
  frontend:
    # image: rapydo/frontend
    build:
      context: ${SUBMODULE_DIR}/build-templates/frontend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: rapydo/frontend:${RAPYDO_VERSION}
    # command: sleep infinity
    hostname: frontend
    # working_dir: /rapydo/
    environment:
      ACTIVATE: 1  # fixed, because it is enabled by frontend.framework variable
      CURRENT_UID: ${CURRENT_UID}
      CURRENT_GID: ${CURRENT_GID}
      APP_MODE: ${APP_MODE}
      MODULE_PATH: /modules
      PROJECT_TITLE: ${PROJECT_TITLE}
      ALLOW_PASSWORD_RESET: "false"
      ALLOW_REGISTRATION: "false"
      BACKEND_PORT: 8080
      BACKEND_HOST: ${PROJECT_DOMAIN}
    volumes:
      - ${PROJECT_DIR}:/app
      - ${SUBMODULE_DIR}/frontend/:/rapydo
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/frontend:/modules

  ###############################
  proxy:
    volumes:
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/frontend:/modules
