ignore:
  - "controller/__main__.py" # cannot be tested
  - "controller/templates"
  - "setup.py"
  - "check_versions.py"
  - "check_ciphers.py"
# fixes:
#   - "before/::after/"  # move path   e.g., "before/path" => "after/path"
