repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    rev: v1.1.0
    hooks:
      - id: forbid-html-img-without-alt-text
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.14.1
    hooks:
      - id: ggshield
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        stages: [manual]
        additional_dependencies:
          [
            "git+https://github.com/rapydo/http-api.git@2.4#egg=rapydo_http[types]",
          ]
        # https://mypy.readthedocs.io/en/stable/command_line.html
        args: [
            # This flag disallows usage of generic types that do not specify explicit type parameters.
            # Moreover, built-in collections (such as list and dict)
            # become disallowed as you should use their aliases from the typing module
            # (such as List[int] and Dict[str, str]).
            "--disallow-any-generics",
            # This flag type checks the body of every function, regardless of whether it has type annotations.
            # (By default the bodies of functions without annotations are not type checked.)
            "--check-untyped-defs",
            "--warn-redundant-casts",
            # "--warn-unused-ignores",
            "--warn-return-any",
            "--warn-unreachable",
            "--warn-unused-configs",

            # This flag reports an error whenever a function with type annotations
            # calls a function defined without annotations
            # -> Call to untyped function "xyz" in typed context
            "--disallow-untyped-calls",

            # This flag reports an error whenever it encounters a
            # function definition without type annotations.
            # -> xyz Function is missing a type annotation
            "--disallow-untyped-defs",

            # This flag reports an error whenever it encounters a
            # partly annotated function definition.
            "--disallow-incomplete-defs",
          ]
