#!/bin/bash

echo "
#####################################################################
This is a wrapper script for Flask-Migrate
https://github.com/miguelgrinberg/Flask-Migrate

This script will proxy every command to flask db by adding 
--directory option for better integration with RAPyDo
#####################################################################

"

if [[ -z $1 ]]; then
	flask db --help
else
	flask db $@ --directory "${PROJECT_NAME}/migrations"
fi