name: Compose

on:
  push:
  # schedule:
  #   - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --no-cache-dir --editable .
          # Needed to make git commit (used by tests) to work and prevent error: 'Author identity unknown'
          git config --global user.email "tests@rapy.do"
          git config --global user.name "RAPyDo"
      - name: Run Compose
        env:
          LOGURU_LEVEL: DEBUG
          TESTING: 1
        run: |
          mkdir rapydo_tests
          cd rapydo_tests
          rapydo create composetest --auth neo4j --frontend angular --service celery --service redis --service rabbit --origin-url https://your_remote_git/your_project.git
          rapydo init
          rapydo dump

          docker-compose up -d
          docker-compose ps
          docker-compose exec -T -d -u developer backend restapi launch
          sleep 25
          docker-compose logs
          curl --silent --insecure -X GET --max-time 5 http://localhost:8080/api/status | grep "Server is alive"
