name: MyPy

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install MyPy
        run: |
          python -m pip install --upgrade pip
          pip install mypy lxml html5lib pytest-stub types-PyYAML types-python-dateutil types-pytz types-requests
          pip install --upgrade --no-cache-dir --editable .

      - name: Run MyPy
        run: |
          echo "[mypy]" > mypy.ini

          for lib in \
            git \
            docker.errors \
            compose \
            plumbum \
            sultan \
            dockerfile_parse \
            ; do
            echo "[mypy-${lib}.*]" >> mypy.ini
            echo "ignore_missing_imports = True" >> mypy.ini
            
          done

          export MYPYPATH='./stubs'
          mypy --disallow-incomplete-defs --disallow-any-unimported --disallow-any-generics --check-untyped-defs --warn-redundant-casts --warn-unused-ignores --warn-unused-configs --warn-return-any --warn-unreachable --txt-report report --html-report report controller/
          cat report/index.txt

      - name: Save Report
        uses: actions/upload-artifact@v2
        with:
          name: mypy-report
          path: report
