name: MyPy

on:
  push:
  pull_request:
  workflow_dispatch:

# Cancel previous running jobs on the same branch in case of new pushs
concurrency:
  group: do-mypy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install MyPy
        run: |
          python -m pip install --upgrade pip
          pip install mypy lxml html5lib types-PyYAML types-python-dateutil types-pytz types-requests types-freezegun Faker
          pip install --upgrade --no-cache-dir --editable .

      - name: Run MyPy
        run: |
          echo "[mypy]" > mypy.ini
          echo "mypy_path = ./stubs" >> mypy.ini

          mypy --disallow-untyped-defs --disallow-incomplete-defs --disallow-any-unimported --disallow-any-generics --check-untyped-defs --disallow-untyped-calls --warn-redundant-casts --warn-unused-ignores --warn-unused-configs --warn-return-any --warn-unreachable --txt-report report --html-report report controller/
          cat report/index.txt

      - name: Save Report
        uses: actions/upload-artifact@v3
        with:
          name: mypy-report
          path: report
