name: MyPy

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install mypy lxml html5lib 
          pip install --upgrade --no-cache-dir --editable .

      - name: MyPy
        run: |
          # --follow-imports=error
          mypy --allow-untyped-globals --warn-redundant-casts --warn-unused-ignores --warn-return-any --warn-unreachable --txt-report . --html-report . controller/
          cat index.txt
