name: MyPy

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install mypy lxml html5lib 
          pip install --upgrade --no-cache-dir --editable .

      - name: MyPy
        run: |
          echo "[mypy]" > mypy.ini

          for lib in \
            glom \
            git \
            docker \
            compose \
            plumbum \
            sultan \
            dockerfile_parse \
            ; do
            echo "[mypy-${lib}.*]" >> mypy.ini
            echo "ignore_missing_imports = True" >> mypy.ini
            
          done

          echo "[mypy-glom.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-git.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-docker.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-compose.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-plumbum.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-sultan.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-dockerfile_parse.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          mypy --warn-redundant-casts --warn-unused-ignores --warn-unused-configs --warn-return-any --warn-unreachable --txt-report . --html-report . controller/
          cat index.txt
